# Generated by Django 5.1.2 on 2024-10-12 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('users', '0002_alter_puser_middle_name_alter_puser_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='puser',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.tariff', verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='puser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
    ]
