# Generated by Django 5.1.2 on 2024-10-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_puser_tariff_alter_puser_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='puser',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
        migrations.AddField(
            model_name='puser',
            name='wallet',
            field=models.FloatField(default=0.0, verbose_name='Баланс'),
        ),
    ]
