# Generated by Django 5.1.2 on 2024-10-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_puser_paid_puser_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='puser',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда оплачено'),
        ),
    ]
