# Generated by Django 5.1.2 on 2024-10-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_puser_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='puser',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к файлу'),
        ),
    ]
