# Generated by Django 5.1.2 on 2024-10-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_puser_number_of_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="puser",
            name="auto_pay",
            field=models.BooleanField(default=0, verbose_name="Автооплата"),
        ),
    ]
