# Generated by Django 5.1.2 on 2024-10-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_tariff_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tariffs', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='ppm',
            field=models.IntegerField(verbose_name='Плата за месяц'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
    ]
