# Generated by Django 5.1.2 on 2024-10-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tutorials', verbose_name='Изображение')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Туториал',
                'verbose_name_plural': 'Туториалы',
            },
        ),
    ]
