# Generated by Django 5.1.2 on 2024-10-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
    ]
